### ISSUE TITLE
how can I obtain the "subject_ID.txt" file in 01-fetch_data.py

### ISSUE THREAD

**Issue by SkyeC77** [xxlya/BrainGNN_Pytorch#1]
there is "shutil.copyfile(os.path.join(root_folder,'subject_ID.txt'), os.path.join(data_folder, 'subject_IDs.txt'))" in 01-fetch_data.py, but there is no corresponding file in the directory, how can I access the subject_ID.txt?  thanks!

**Comment by xxlya** [comment]
I've uploaded the file to 'data/subsjuct_ID.txt' Thanks :)
