### ISSUE TITLE
can you supply a download link of the pre-processed data for the HCP dataset?

### ISSUE THREAD

**Issue by SkyeC77** [xxlya/BrainGNN_Pytorch#2]
I want to do experiments on the HCP dataset, but the original task-fMRI data for task state classification are so large and it's hard to download, so could you supply a link for the processed time series data or graphs? Thank you!

**Comment by xxlya** [comment]
Hi, I am sorry that I worked on a preprocessed version of HCP data own by one of our collaborators. I am not sure if it is sharable at the current stage but I'll check.

**Comment by mariliarosa4** [comment]
Please, let us know if the processed dataset is available :)
