### ISSUE TITLE
Size of scores

### ISSUE THREAD

**Issue by mariliarosa4** [xxlya/BrainGNN_Pytorch#5]
Hi dear, I'm trying to visualize scores in brain atlas, but score1 has shape 100, and score2 has shape 50, even I'm using abide processed with cc200 atlas. Is that correct?

**Comment by xxlya** [comment]
The dims are correct. With default pooling ratio =0.5, score 1 give top 100 important ROIs of cc200. You can simply set the others as 0 because you may not  care about the unimportant ones.

Best,
Xiaoxiao

**Comment by mariliarosa4** [comment]
Make sense...so, the variable "perm" return the index ROI correspondent to respective score in array position?

**Comment by xxlya** [comment]
Sorry that I missed this msg. Yes!
