### ISSUE TITLE
Question about how vertices are defined

### ISSUE THREAD

**Issue by quanmai** [xxlya/BrainGNN_Pytorch#9]
First of all, thanks for sharing the source code.

I have a question about how you define vertices. Each node / vertice has dimension of (#number of ROIS), so is that relative position of that ROI to other ROIs, say Euclidian distance? Thank you.

**Comment by xxlya** [comment]
Nodes are defined as brain ROIs, for which we used the existing brain atlas for the parcellation. Hope this answer is helpful. Pls feel free to let me know if you have any questions. Thanks!

**Comment by quanmai** [comment]
Thanks for your prompt reply, and my apology for unclear question. I mean, how nodes feature are defined? As I am seeing that node vector feature has the dimension of number of ROIs, say 268 for HPC dataset. Is it relative position to other 267 parcellations and to itself (zero)?

**Comment by xxlya** [comment]
I see your points now. Sorry for the confusion. We simply took a row of Pearson correlation matrix as the node feature. For example, the v-th node takes the v-th row of the Pearson correlation matrix calculated using all ROIs.

**Comment by quanmai** [comment]
Thanks for your clarification. Keep up the good work!
